# -*- coding: utf-8 -*-
"""Salary Estimate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_K-swU2ejRx2NR2tU1OuX2gTC_5sKjA

## Data Import from Bigquery
"""

from google.colab import auth
auth.authenticate_user()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext google.colab.data_table
from google.cloud import bigquery

project = bigquery.Client(project = "linkedin-job-postings-2324")

import pandas as pd

# Google Cloud Proje ID'niz
project_id = 'linkedin-job-postings-2324'

# Çalıştırmak istediğiniz SQL sorgusu
query = """
SELECT
  title,
  city,
  state,
 formatted_work_type,
 formatted_experience_level,
 remote_allowed,
 pay_period,
 normalized_salary
FROM `linkedin-job-postings-2324.dbt_serbas.mart_postings`
"""

df= project.query(query).to_dataframe()

df.head()

df.info()

df.shape

(df.isnull().sum() > 0).sum()

df.isnull().mean().sort_values(ascending=False)[0:6].plot(kind="bar")

df = df[df["normalized_salary"].notna()]
df

print("Toplam veri:", len(df))
print("Model için kalan veri:", len(df))

# YOUR CODE HERE
(df.isnull().sum() > 0).sum()

df.isnull().mean().sort_values(ascending=False)[0:4].plot(kind="bar")

df.info()

df["remote_allowed"] = df["remote_allowed"].fillna(False).astype(int)
df["remote_allowed"].value_counts(normalize=True) * 100

df.isnull().mean().sort_values(ascending=False)[0:16].plot(kind="bar")

df['normalized_salary'].describe()

Q1 = df['normalized_salary'].quantile(0.25)
Q3 = df['normalized_salary'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
df_clean = df[(df['normalized_salary'] >= lower_bound) & (df['normalized_salary'] <= upper_bound)].copy()

df_clean

df_clean.shape

"""## X ve y i seçme

"""

y= df_clean['normalized_salary']
X = df_clean.drop(columns=['normalized_salary'])

X

"""## Train Test

"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train,y_test = train_test_split(X,y,test_size= 0.2, random_state=42)

"""## Imputed et

"""

from sklearn.impute import SimpleImputer
num_imputer = SimpleImputer(strategy='mean').set_output(transform='pandas')

X_train_num = X_train.select_dtypes(include = 'number')
X_test_num = X_test.select_dtypes(include = 'number')

X_train_num_imputed = num_imputer.fit_transform(X_train_num)
X_test_num_imputed = num_imputer.transform(X_test_num)

assert X_train_num_imputed.isnull().sum().sum() == 0
assert X_test_num_imputed.isnull().sum().sum() == 0

cat_imputer = SimpleImputer(strategy="most_frequent").set_output(transform="pandas")

X_train_cat = X_train.select_dtypes(exclude = 'number')
X_test_cat =X_test.select_dtypes(exclude ='number')

# city ve state sütunlarında boşluklar yüzünden hata aldık. bunu çözmek için None değerleri Nan olarak güncelledik ve sonra impute ettik.
import numpy as np

X_train_cat = X_train_cat.replace({None: np.nan})
X_test_cat = X_test_cat.replace({None: np.nan})

# kategorik olarak ımpute edildi. eksik değerler dolduruldu.
X_train_cat_imputed = cat_imputer.fit_transform(X_train_cat)
X_test_cat_imputed = cat_imputer.transform(X_test_cat)

assert X_train_cat_imputed.isnull().sum().sum() == 0
assert X_test_cat_imputed.isnull().sum().sum() == 0

X_train_cat_imputed.shape

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().set_output(transform="pandas")

X_train_num_scaled = scaler.fit_transform(X_train_num_imputed)
X_test_num_scaled = scaler.transform(X_test_num_imputed)

assert X_train_num_scaled.isnull().sum().sum() == 0
assert X_test_num_scaled.isnull().sum().sum() == 0

"""## Encoding

"""

from sklearn.preprocessing import OneHotEncoder

#encoder = OneHotEncoder(sparse_output=False, handle_unknown="ignore").set_output(transform="pandas")
#X_train_cat_encoded = encoder.fit_transform(X_train_cat_imputed)
#X_test_cat_encoded = encoder.transform(X_test_cat_imputed)

# title sütununda çok fazla unique kategori olduğu için encoder .ok fazla sütun oluşturdu. bu yüzden 20 den az olanları birleştirip sütun sayısını optimize etmeye çalıştık.
encoder = OneHotEncoder(handle_unknown="infrequent_if_exist",
                        min_frequency=20,
                        sparse_output=False
                        ).set_output(transform="pandas")

X_train_cat_encoded = encoder.fit_transform(X_train_cat_imputed)
X_test_cat_encoded = encoder.transform(X_test_cat_imputed)

X_train_cat_imputed.nunique().sort_values(ascending=False)

X_train_cat_encoded.shape

"""## modeli oluştur

"""

X_train_preproc = pd.concat([X_train_num_scaled, X_train_cat_encoded], axis=1)
X_test_preproc = pd.concat([X_test_num_scaled, X_test_cat_encoded], axis=1)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_preproc,y_train)
model.score(X_test_preproc,y_test)

from sklearn.metrics import mean_absolute_error
y_pred = model.predict(X_test_preproc)
mean_absolute_error(y_test, y_pred)